### ISSUE TITLE
500 Error while fetching models from OpenAI API

### ISSUE THREAD

**Issue by OlegYurchik** [adrianliechti/wingman#8]
![image](https://github.com/adrianliechti/llama/assets/8088382/98e3e233-7839-4480-bbbb-dc6810f485ba)
In logs:
```
practical_jess-main_app-1  | 2023/12/01 07:29:31 "GET http://192.168.1.2:3041/v1/models HTTP/1.1" from 172.17.0.1:46460 - 500 0B in 23.723753ms
practical_jess-main_app-1  | 2023/12/01 07:29:35 "GET http://192.168.1.2:3041/v1/models HTTP/1.1" from 172.17.0.1:47558 - 500 0B in 23.491043ms
practical_jess-main_app-1  | 2023/12/01 07:31:00 "GET http://192.168.1.2:3041/v1/models HTTP/1.1" from 172.17.0.1:45258 - 500 0B in 25.367463ms
practical_jess-main_app-1  | 2023/12/01 07:31:01 "GET http://192.168.1.2:3041/v1/models HTTP/1.1" from 172.17.0.1:45258 - 500 0B in 20.156412ms
```
Docker-compose for OpenAI API
```
name: practical_jess
services:
  main_app:
    cpu_shares: 10
    command: []
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - LLAMA_URL=http://192.168.1.2:3040
    image: adrianliechti/llama-openai
    ports:
      - target: 8080
        published: "3041"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
```
Docker compose for ChatBot UI
```
name: ecstatic_et
services:
  main_app:
    cpu_shares: 10
    command: []
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - DEFAULT_MODEL=default
      - OPENAI_API_KEY=none
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    ports:
      - target: 3000
        published: "3042"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
```
